--- 
title: "CM 2110 Calculus and Statistical Distributions"
author: "Dr. Priyanga D. Talagala"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::pdf_book
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
#- \fancyhead[CO,CE]{This is fancy header}
- \fancyfoot[CO,CE]{Prepared by Dr. Priyanga D. Talagala}
- \fancyfoot[LE,RO]{\thepage}
- \usepackage{wrapfig}
#- \usepackage{float}
- \usepackage{floatrow}
- \floatplacement{figure}{H}
- \floatplacement{table}{H}
- \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
- \usepackage{mathtools}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

# Course Syllabus {-}

## Pre-requisites {-}

CM 1110

**Remark:**

*This course module contains two main sections: (1) mathematics and (2) statistics. This syllabus is designed for the statistics section. Lectures for mathematics section and statistics section are conducted  by two lecturers as two separate sub modules (1.5 hour lectures/Week). End Semester Examination is conducted as a single examination.*

## Learning Outcomes {-}

On successful completion of this module, students will be able to plan more carefully the design of experiment in advance which provide evidence for or against theories of cause and effect and make inferences about population characteristics based on sample information and thereby solve data analysis problems in different application domains.  (R(https://cran.r-project.org/) and RStudio are also freely available to install on your own computer). Get the Open Source Edition of RStudio Desktop. RStudio allows you to run R in a more user-friendly environment.


## Outline Syllabus {-}

- Functions of Several Variables
- Linear Algebra
- Coordinate Systems & Vectors
- Differential Equations
-	**Statistical Distributions**
-	**Estimation**
-	**Hypothesis Testing**
- **Contingency tables**
-	**Design of Experiments**



## Method of Assessment {-}

- Mid-semester examination 
- End-semester examination 


## Recommended Texts {-}

- Casella, G., & Berger, R. L. (2002). Statistical inference (Vol. 2, pp. 337-472). Pacific Grove, CA: Duxbury.
- Mood, A.M., Graybill, F.A. and Boes, D.C. (2007): Introduction to the Theory of Statistics, 3rd Edn.
(Reprint). Tata McGraw-Hill Pub. Co. Ltd. 
- Montgomery, D. C. (2017). Design and analysis of experiments. John wiley \& sons.



## Lecturer {-}

Dr. Priyanga D. Talagala

## Schedule {-}

Lectures: 

- Friday [9.15 am - 10.45 am]

Tutorial:

- Friday [11.00 am - 12.30 pm]

Consultation time: 

- Friday [8.15 am to 9.00 am]


